// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appTitle => 'Wealth 360';

  @override
  String get navHome => 'Home';

  @override
  String get navBudget => 'Budget';

  @override
  String get navAnalysis => 'Analysis';

  @override
  String get navRetirement => 'Retirement';

  @override
  String get navSimulators => 'Tools';

  @override
  String get navProfile => 'Profile';

  @override
  String get totalGrossWealth => 'TOTAL GROSS WEALTH';

  @override
  String get netWealth => 'Net wealth';

  @override
  String get investedAmount => 'Invested amount';

  @override
  String get investedPart => 'Invested part';

  @override
  String get performance => 'Performance';

  @override
  String get globalPerformance => 'Global performance';

  @override
  String get detailsPatrimoine => 'Wealth details';

  @override
  String get netWealthConstituted => 'Constituted net wealth';

  @override
  String get netWealthEstimated => 'Estimated net wealth';

  @override
  String get analysisTitle => 'STRATEGIC ANALYSIS';

  @override
  String get independencePilot => 'Independence Pilot';

  @override
  String get monthlyGains => 'ESTIMATED MONTHLY GAINS';

  @override
  String get averageGenerated => 'Average generated by your assets';

  @override
  String get needs => 'NEEDS';

  @override
  String get growth => 'GROWTH';

  @override
  String get liberty => 'FREEDOM';

  @override
  String get expenseCoverage => 'EXPENSE COVERAGE';

  @override
  String get investmentCoverage => 'INVESTMENT COVERAGE';

  @override
  String get salaryCoverage => 'SALARY COVERAGE';

  @override
  String get progression => 'Progression';

  @override
  String get objective => 'Objective';

  @override
  String get appearance => 'APPEARANCE';

  @override
  String get theme => 'App Theme';

  @override
  String get themeLight => 'Light';

  @override
  String get themeDark => 'Dark';

  @override
  String get themeSystem => 'Adaptive';

  @override
  String get language => 'App Language';

  @override
  String get languageSystem => 'System';

  @override
  String get notifications => 'NOTIFICATIONS';

  @override
  String get dailySummary => 'Daily summary (7pm)';

  @override
  String get testNotification => 'TEST NOTIFICATION NOW';

  @override
  String get financialProfile => 'FINANCIAL PROFILE';

  @override
  String get monthlySalary => 'Monthly net salary';

  @override
  String get monthlyInvestment => 'Monthly investment';

  @override
  String get account => 'MY ACCOUNT';

  @override
  String get about => 'About';

  @override
  String get version => 'App version';

  @override
  String get logout => 'LOGOUT';

  @override
  String get cancel => 'CANCEL';

  @override
  String get delete => 'DELETE';

  @override
  String get deleteTitle => 'Delete ?';

  @override
  String confirmDelete(Object name) {
    return 'Are you sure you want to delete \'\'$name\'\' ?';
  }

  @override
  String get noAccountsAvailable => 'No accounts available';

  @override
  String get usePlusButtonToStart => 'Use the + button to start';

  @override
  String get monthlyBudget => 'MONTHLY BUDGET';

  @override
  String get financialFlows => 'Financial flows';

  @override
  String get income => 'INCOME';

  @override
  String get expenses => 'EXPENSES';

  @override
  String get noIncomeReported => 'No income reported';

  @override
  String get noExpenseReported => 'No expense reported';

  @override
  String get other => 'Other';

  @override
  String get addFlow => 'Add flow';

  @override
  String get editFlow => 'Edit flow';

  @override
  String get incomeType => 'INCOME';

  @override
  String get expenseType => 'EXPENSE';

  @override
  String get label => 'Label';

  @override
  String get monthlyAmount => 'Monthly amount';

  @override
  String get category => 'Category';

  @override
  String get save => 'SAVE';

  @override
  String get update => 'UPDATE';

  @override
  String get retirementFire => 'RETIREMENT & FIRE';

  @override
  String get freedomGoal => 'Freedom Goal';

  @override
  String get grossAnnualSimulations => 'Simulations in gross annual.';

  @override
  String get yourAssumptions => 'YOUR ASSUMPTIONS';

  @override
  String get desiredIncome => 'Desired income';

  @override
  String get estimatedPension => 'Estimated pension';

  @override
  String get rate => 'Rate';

  @override
  String get needAndTarget => 'NEED & TARGET';

  @override
  String get toFinance => 'TO FINANCE';

  @override
  String get targetCapital => 'TARGET CAPITAL';

  @override
  String capitalGenerationInfo(Object amount, Object rate) {
    return 'With a rate of $rate%, this capital generates $amount / year.';
  }

  @override
  String get pensionCoversGoal => 'Your pension already covers your goal.';

  @override
  String get current => 'Current';

  @override
  String reachedPercent(Object percent) {
    return '$percent% reached';
  }

  @override
  String remainingAmount(Object amount) {
    return 'Remaining: $amount';
  }

  @override
  String get resources => 'RESOURCES';

  @override
  String get retirementInsurance => 'Retirement Insurance';

  @override
  String get estimatePensionOfficialSite =>
      'Estimate my pension on the official site';

  @override
  String get fillDesiredIncomePrompt =>
      'Fill in your desired income to project your target capital.';

  @override
  String get projectionTools => 'PROJECTION TOOLS';

  @override
  String get simulators => 'Simulators';

  @override
  String get realEstateSimulator => 'Real Estate Simulator';

  @override
  String get calculatePurchaseCapacity =>
      'Calculate your real purchase capacity';

  @override
  String get retirementSimulator => 'Retirement Simulator';

  @override
  String get projectIndependence => 'Project your financial independence';

  @override
  String get realEstate => 'REAL ESTATE';

  @override
  String get simulator => 'Simulator';

  @override
  String get maxPurchaseCapacity => 'MAXIMUM PURCHASE CAPACITY';

  @override
  String get monthlyPayment => 'Monthly payment';

  @override
  String get maxLoan => 'Maximum Loan';

  @override
  String get yourFinancialProfile => 'YOUR FINANCIAL PROFILE';

  @override
  String get personalDownPayment => 'Personal Down Payment';

  @override
  String get loanParameters => 'LOAN PARAMETERS';

  @override
  String get duration => 'Duration';

  @override
  String get interestRate => 'Interest Rate';

  @override
  String get exploreMarket => 'EXPLORE THE MARKET';
}
